# Generated by Django 5.1 on 2024-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_livro_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='descricao_livro',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Livro'),
        ),
    ]
