# Generated by Django 5.1 on 2024-09-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_livro_descricao_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='instituicao',
            field=models.CharField(default='IFRN', max_length=100, verbose_name='Instituição'),
        ),
    ]
